import { P } from './index';

export const MODULE_ACCESS_PERMS = [
  P.MODULE_SOURCE_ACCESS,
  P.MODULE_FORGE_ACCESS,
  P.MODULE_VERIFY_ACCESS,
  P.MODULE_DEPLOY_ACCESS,
];

export const SYSTEM_MANAGEMENT_PERMS = [
  P.MANAGE_SYSTEM,
  P.VIEW_REPORTS,
  P.MANAGE_OPS,
  P.ADMIN_USERS_MANAGE,
  P.ADMIN_ROLES_MANAGE,
];

export const DEPLOY_MANAGEMENT_PERMS = [
  P.DEPLOY_EMP_VIEW_LIST,
  P.DEPLOY_EMP_VIEW_TEAM,
  P.DEPLOY_EMP_VIEW_PROFILE,
  P.DEPLOY_EMP_VIEW_PROFILE_SENSITIVE,
  P.DEPLOY_EMP_VIEW_PROFILE_FINANCIAL,
  P.DEPLOY_EMP_CREATE,
  P.DEPLOY_EMP_OFFBOARD,
  P.DEPLOY_EMP_DELETE,
  P.DEPLOY_EMP_EDIT_BASIC,
  P.DEPLOY_EMP_EDIT_JOB,
  P.DEPLOY_EMP_EDIT_FINANCIAL,
  P.DEPLOY_EMP_APPROVE_BASIC,
  P.DEPLOY_EMP_APPROVE_SENSITIVE,
  P.DEPLOY_EMP_APPROVE_FINANCIAL,
  P.DEPLOY_EMP_EXPORT,
  P.DEPLOY_EMP_MANAGE_DOCS,
  P.DEPLOY_ASSETS_VIEW_ALL,
  P.DEPLOY_ASSETS_MANAGE_ONBOARDING,
  P.DEPLOY_ASSETS_MANAGE_CLEARANCE,
  P.DEPLOY_ASSETS_EXPORT_REPORTS,
  P.DEPLOY_ATT_VIEW_TEAM,
  P.DEPLOY_ATT_VIEW_ALL,
  P.DEPLOY_ATT_APP_CORRECTION,
  P.DEPLOY_ATT_MANAGE_POLICIES,
  P.DEPLOY_LEAVES_VIEW_TEAM,
  P.DEPLOY_LEAVES_VIEW_ALL,
  P.DEPLOY_LEAVES_APPROVE,
  P.DEPLOY_LEAVES_MANAGE_BALANCES,
  P.DEPLOY_ONBOARD_VIEW,
  P.DEPLOY_ONBOARD_SEND_INVITE,
  P.DEPLOY_ONBOARD_CANCEL_INVITE,
  P.DEPLOY_ONBOARD_REVIEW_SUBMISSIONS,
  P.DEPLOY_PAYROLL_VIEW_ALL,
  P.DEPLOY_PAYROLL_RUN_PAYROLL,
  P.DEPLOY_PAYROLL_EDIT_RECORDS,
  P.DEPLOY_PAYROLL_UPLOAD_BULK,
  P.DEPLOY_PAYROLL_APPROVE,
  P.DEPLOY_PAYROLL_EXPORT_REPORTS,
  P.DEPLOY_PERF_VIEW_TEAM,
  P.DEPLOY_PERF_VIEW_ALL,
  P.DEPLOY_PERF_ASSIGN_KRAS,
  P.DEPLOY_PERF_SUBMIT_MANAGER,
  P.DEPLOY_PERF_MANAGE_ASSESSMENTS,
  P.DEPLOY_PERF_EXPORT_REPORTS,
  P.DEPLOY_ASSESS_MANAGE,
  P.DEPLOY_TRAIN_MANAGE,
  P.DEPLOY_DASH_ADMIN,
  P.DEPLOY_NOTIF_ADMIN,
  P.DEPLOY_NOTIF_MANAGE,
];

export const DEPLOY_PERSONAL_PERMS = [
  P.DEPLOY_ASSETS_VIEW_PERSONAL,
  P.DEPLOY_ATT_VIEW_PERSONAL,
  P.DEPLOY_ATT_CLOCK_IN_OUT,
  P.DEPLOY_ATT_REQ_CORRECTION,
  P.DEPLOY_LEAVES_VIEW_PERSONAL,
  P.DEPLOY_LEAVES_REQUEST,
  P.DEPLOY_PAYROLL_VIEW_PERSONAL,
  P.DEPLOY_PERF_VIEW_PERSONAL,
  P.DEPLOY_PERF_SUBMIT_SELF,
  P.DEPLOY_ASSESS_VIEW,
  P.DEPLOY_TRAIN_VIEW,
];

export const SOURCE_MANAGEMENT_PERMS = [
  P.SOURCE_JOBS_VIEW,
  P.SOURCE_JOBS_MANAGE,
  P.SOURCE_CANDIDATES_VIEW,
  P.SOURCE_CANDIDATES_MANAGE,
  P.SOURCE_OFFERS_VIEW,
  P.SOURCE_OFFERS_MANAGE,
  P.SOURCE_OFFERS_APPROVE,
  P.SOURCE_EVALUATIONS_MANAGE,
  P.SOURCE_INTERVIEWS_MANAGE,
];

export const VERIFY_MANAGEMENT_PERMS = [
  P.VERIFY_ASSESS_VIEW,
  P.VERIFY_ASSESS_MANAGE,
  P.VERIFY_ASSESS_ASSIGN,
  P.VERIFY_QUESTIONS_VIEW,
  P.VERIFY_QUESTIONS_MANAGE,
  P.VERIFY_MONITORING_VIEW,
  P.VERIFY_RESULTS_VIEW,
  P.VERIFY_RESULTS_MANAGE,
  P.VERIFY_QUERIES_MANAGE,
];

export const FORGE_MANAGEMENT_PERMS = [
  P.FORGE_COURSES_MANAGE,
];

export const FORGE_PERSONAL_PERMS = [
  P.FORGE_COURSES_VIEW,
  P.FORGE_ENROLL,
];

export const ALL_MANAGEMENT_PERMS = [
  ...SYSTEM_MANAGEMENT_PERMS,
  ...DEPLOY_MANAGEMENT_PERMS,
  ...SOURCE_MANAGEMENT_PERMS,
  ...VERIFY_MANAGEMENT_PERMS,
  ...FORGE_MANAGEMENT_PERMS,
];

export const ALL_PERSONAL_PERMS = [
  ...DEPLOY_PERSONAL_PERMS,
  ...FORGE_PERSONAL_PERMS,
];
