from typing import List, Optional, Dict, Any
from backend.core.database import get_db_connection
from psycopg2.extras import RealDictCursor

class AttendanceRepository:
    def get_todays_attendance(self, employee_code: str, date: str) -> Optional[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute(
                "SELECT * FROM attendance WHERE employee_code = %s AND date = %s", 
                (employee_code, date)
            )
            row = cur.fetchone()
            return dict(row) if row else None
        finally:
            conn.close()

    def clock_in(self, employee_code: str, date: str, time: str, ip: str):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            cur.execute('''
                INSERT INTO attendance (employee_code, date, clock_in, ip_address, status)
                VALUES (%s, %s, %s, %s, 'Present')
            ''', (employee_code, date, time, ip))
            conn.commit()
        finally:
            conn.close()

    def clock_out(self, employee_code: str, date: str, time: str, work_log: str):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            cur.execute('''
                UPDATE attendance 
                SET clock_out = %s, work_log = %s
                WHERE employee_code = %s AND date = %s
            ''', (time, work_log, employee_code, date))
            conn.commit()
        finally:
            conn.close()

    def get_history(self, employee_code: str, limit: int = 30) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute('''
                SELECT * FROM attendance 
                WHERE employee_code = %s 
                ORDER BY date DESC LIMIT %s
            ''', (employee_code, limit))
            records = cur.fetchall()
            return [dict(r) for r in records]
        finally:
            conn.close()

    def get_leave_balance(self, employee_code: str, year: int) -> Optional[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute(
                "SELECT * FROM leave_balances WHERE employee_code = %s AND year = %s",
                (employee_code, year)
            )
            row = cur.fetchone()
            return dict(row) if row else None
        finally:
            conn.close()

    def create_leave_balance(self, employee_code: str, year: int):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO leave_balances (employee_code, year) VALUES (%s, %s)",
                (employee_code, year)
            )
            conn.commit()
        finally:
            conn.close()
    
    def update_leave_balance(self, employee_code: str, column: str, days: int):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            # Note: column names are safe here as they are internally generated by the service
            query = f"UPDATE leave_balances SET {column} = {column} + %s WHERE employee_code = %s"
            cur.execute(query, (days, employee_code))
            conn.commit()
        finally:
            conn.close()

    def create_leave_request(self, employee_code: str, start: str, end: str, l_type: str, reason: str, status: str = 'Pending'):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            cur.execute('''
                INSERT INTO leaves (employee_code, start_date, end_date, leave_type, reason, status)
                VALUES (%s, %s, %s, %s, %s, %s)
            ''', (employee_code, start, end, l_type, reason, status))
            conn.commit()
        finally:
            conn.close()

    def get_employee_leaves(self, employee_code: str) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute(
                "SELECT * FROM leaves WHERE employee_code = %s ORDER BY applied_at DESC", 
                (employee_code,)
            )
            leaves = cur.fetchall()
            return [dict(l) for l in leaves]
        finally:
            conn.close()

    def get_all_pending_leaves(self, admin_role: str, admin_code: Optional[str]) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            query = '''
                SELECT l.*, e.name as employee_name, COALESCE(u.role, 'Employee') as applicant_role
                FROM leaves l 
                JOIN employees e ON l.employee_code = e.employee_code 
                LEFT JOIN users u ON l.employee_code = u.employee_code
                WHERE l.status = 'Pending'
            '''
            params = []
            
            # HR should not approve Admin or other HR's leaves
            if admin_role == 'HR':
                query += " AND COALESCE(u.role, 'Employee') NOT IN ('Admin', 'HR')"
            
            # Approvers should not see their own leave in the approval queue
            if admin_code:
                query += " AND l.employee_code != %s"
                params.append(admin_code)
                
            query += " ORDER BY l.applied_at ASC"
            
            cur.execute(query, params)
            leaves = cur.fetchall()
            return [dict(l) for l in leaves]
        finally:
            conn.close()
            
    def get_leave_by_id(self, leave_id: int) -> Optional[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute("SELECT * FROM leaves WHERE id = %s", (leave_id,))
            row = cur.fetchone()
            return dict(row) if row else None
        finally:
            conn.close()

    def update_leave_status(self, leave_id: int, status: str, reason: Optional[str]):
        conn = get_db_connection()
        try:
            cur = conn.cursor()
            cur.execute("UPDATE leaves SET status = %s, rejection_reason = %s WHERE id = %s", (status, reason, leave_id))
            conn.commit()
        finally:
            conn.close()

    def get_daily_log(self, date: str) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute('''
                SELECT a.*, e.name as employee_name, e.designation 
                FROM attendance a
                JOIN employees e ON a.employee_code = e.employee_code 
                WHERE a.date = %s
            ''', (date,))
            logs = cur.fetchall()
            return [dict(l) for l in logs]
        finally:
            conn.close()

    def get_monthly_attendance(self, start_date: str, end_date: str) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
             cur = conn.cursor(cursor_factory=RealDictCursor)
             cur.execute("""
                SELECT employee_code, date, status, clock_in, clock_out
                FROM attendance 
                WHERE date BETWEEN %s AND %s
            """, (start_date, end_date))
             rows = cur.fetchall()
             return [dict(r) for r in rows]
        finally:
            conn.close()

    def get_monthly_approved_leaves(self, start_date: str, end_date: str) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute("""
                SELECT employee_code, start_date, end_date, leave_type
                FROM leaves 
                WHERE status = 'Approved' 
                AND (
                    (start_date BETWEEN %s AND %s) OR 
                    (end_date BETWEEN %s AND %s)
                )
            """, (start_date, end_date, start_date, end_date))
            rows = cur.fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()
            
    def get_all_active_employees_basic(self) -> List[Dict[str, Any]]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute("SELECT name, employee_code FROM employees WHERE employment_status = 'Active' ORDER BY name")
            rows = cur.fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()

    def get_user_role(self, employee_code: str) -> Optional[str]:
        conn = get_db_connection()
        try:
            cur = conn.cursor(cursor_factory=RealDictCursor)
            cur.execute("SELECT role FROM users WHERE employee_code = %s", (employee_code,))
            row = cur.fetchone()
            return row['role'] if row else None
        finally:
             conn.close()

